name: First Workflow

run-name: ${{github.actor}}

on:
 fork:
    types: [created]

jobs:
 job1:
  runs-on: ubuntu-latest
  steps: 
    - run: echo "display the workflow for ubuntu"
 job2:
  runs-on: ubuntu-latest
  steps: 
    - run: echo "display the workflow for ubuntu-2"
